
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DELIMITER = 4;
  public static final int SMALLER_OR_EQUAL = 40;
  public static final int GREATER_OR_EQUAL = 42;
  public static final int ASSIGNMENT = 48;
  public static final int LEFT_CUR_PARENTHESES = 11;
  public static final int UMINUS = 49;
  public static final int STRING_RESERVED = 10;
  public static final int NOT_EQUAL = 45;
  public static final int SMALLER = 41;
  public static final int INTEGER = 18;
  public static final int GREATER = 43;
  public static final int RIGHT_SQUARE_BRACKETS = 16;
  public static final int CONTINUE = 26;
  public static final int INT = 8;
  public static final int MINUS = 34;
  public static final int STATIC = 6;
  public static final int LEFT_PARENTHESES = 13;
  public static final int NOT = 46;
  public static final int AND = 38;
  public static final int OR = 39;
  public static final int MULTIFICATION = 35;
  public static final int COMMA = 17;
  public static final int CLASS = 5;
  public static final int PLUS = 33;
  public static final int IF = 22;
  public static final int THIS = 27;
  public static final int DOT = 47;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 21;
  public static final int EQUAL = 44;
  public static final int TRUE = 30;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MODULO = 37;
  public static final int NULL = 32;
  public static final int BREAK = 25;
  public static final int RIGHT_CUR_PARENTHESES = 12;
  public static final int VOID = 7;
  public static final int LEFT_SQUARE_BRACKETS = 15;
  public static final int RIGHT_PARENTHESES = 14;
  public static final int ELSE = 23;
  public static final int WHILE = 24;
  public static final int CLASS_ID = 2;
  public static final int EXTENDS = 20;
  public static final int STRING = 19;
  public static final int FALSE = 31;
  public static final int DIVISION = 36;
  public static final int LENGTH = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS_ID",
  "ID",
  "DELIMITER",
  "CLASS",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "STRING_RESERVED",
  "LEFT_CUR_PARENTHESES",
  "RIGHT_CUR_PARENTHESES",
  "LEFT_PARENTHESES",
  "RIGHT_PARENTHESES",
  "LEFT_SQUARE_BRACKETS",
  "RIGHT_SQUARE_BRACKETS",
  "COMMA",
  "INTEGER",
  "STRING",
  "EXTENDS",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "LENGTH",
  "TRUE",
  "FALSE",
  "NULL",
  "PLUS",
  "MINUS",
  "MULTIFICATION",
  "DIVISION",
  "MODULO",
  "AND",
  "OR",
  "SMALLER_OR_EQUAL",
  "SMALLER",
  "GREATER_OR_EQUAL",
  "GREATER",
  "EQUAL",
  "NOT_EQUAL",
  "NOT",
  "DOT",
  "ASSIGNMENT",
  "UMINUS"
  };
}

